CREATE TABLE [Game]
(
	[Id] INT IDENTITY,
	[TournamentId] INT NOT NULL,
	[WhiteId] INT NOT NULL,
	[BlackId] INT NOT NULL,
	[Round] TINYINT NOT NULL,
	[Winner] TINYINT NOT NULL DEFAULT 1,

	CONSTRAINT PK_GAME_ID PRIMARY KEY ([Id]),
	CONSTRAINT FK_GAME_TOURNAMENT_ID FOREIGN KEY ([TournamentId]) REFERENCES [Tournament]([Id]),
	CONSTRAINT FK_GAME_WHITE_ID FOREIGN KEY ([WhiteId]) REFERENCES [User]([Id]),
	CONSTRAINT FK_GAME_BLACK_ID FOREIGN KEY ([BlackId]) REFERENCES [User]([Id]),
)
