CREATE TABLE [MM_Tournament_Registration]
(
	[Id] INT IDENTITY,
	[UserId] INT NOT NULL,
	[TournamentId] INT NOT NULL,

	CONSTRAINT PK_MM_TOURNAMENT_REGISTRATION_ID PRIMARY KEY ([Id]),
	CONSTRAINT FK_MM_TOURNAMENT_REGISTRATION_USER FOREIGN KEY ([UserId]) REFERENCES [User]([Id]),
	CONSTRAINT FK_MM_TOURNAMENT_REGISTRATION_TOURNAMENT FOREIGN KEY ([TournamentId]) REFERENCES [Tournament]([Id])
)
