CREATE TABLE [MM_Tournament_Category]
(
	[Id] INT IDENTITY,
	[TournamentId] INT NOT NULL,
	[CategoryId] INT NOT NULL,

	CONSTRAINT PK_MM_TOURNAMENT_CATEGORY PRIMARY KEY ([Id]),

	CONSTRAINT FK_MM_TOURNAMENT_CATEGORY_TOURNAMENT FOREIGN KEY ([TournamentId]) REFERENCES [Tournament]([Id]),
	CONSTRAINT FK_MM_TOURNAMENT_CATEGORY_CATEGORY FOREIGN KEY ([CategoryId]) REFERENCES [Tournament_category]([Id])
)
