CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY,
	[Username] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[Password] NVARCHAR(255) NOT NULL,
	[Date_of_birth] DATETIME NOT NULL,
	[Gender] CHAR(1) NOT NULL,
	[Elo] INT NOT NULL DEFAULT 1200,
	[Role] INT NOT NULL,

	CONSTRAINT PK_USER_ID PRIMARY KEY ([Id]),
	CONSTRAINT UK_USER_USERNAME UNIQUE ([Username]),
	CONSTRAINT UK_USER_EMAIL UNIQUE ([Email]),
	CONSTRAINT FK_USER_ROLE FOREIGN KEY ([Id]) REFERENCES [Role]([Id])

)
